### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by sunoru** [sunoru/Random123.jl#20]
Currently the implementation of AES-NI and ARM completely depends on the AES-NI instruction sets (`llvm.x86.aesni.*`) provided by Intel processors. As Apple Silicon becomes very popular, it would be very nice if ARM64 platforms can also be supported.

**Comment by pthariensflame** [comment]
I have a WIP branch doing the conversion, but tests are failing at the moment.  Part of what makes this more difficult than it should be is that while both Arm(64) and x86(_64) have their own acceleration instructions for AES, those instructions *do different things*.  (Arm breaks them into smaller and more flexible pieces than x86 does and omits the keygen facilities completely.) 

Trying to rebuild the x86 versions from the Arm versions has indeed been done in projects like [SIMD-Everywhere](https://github.com/simd-/simde) and [SSE2NEON](https://github.com/DLTcollab/sse2neon), but consulting those hasn't helped me make things work; the algorithms in this package rely on some pretty specific aspects of the x86 implementation it seems.  The original C++ version of Random123 also doesn't support Arm intrinsics, so we'd be the first to try this.

**Comment by pthariensflame** [comment]
If you want to play around it with, the LLVM intrinsics for 64-bit Arm AES acceleration are `llvm.aarch64.crypto.aes*`, where the `*` is one of `e`, `d`, `mc`, or `imc`.  Any 64-bit Arm machine with NIST crypto (`FEAT_AES`) enabled should execute those just fine; even a RasPi 4 or 5, or a legacy AWS Graviton 1 instance, would do.

EDIT:  Or QEMU!

**Comment by sunoru** [comment]
Thank you so much! The suggestions look really helpful and I will also look into them.

**Comment by pthariensflame** [comment]
@sunoru See #21!  🎉
