### ISSUE TITLE
Build failure on ARM aarch64 with Julia v1.6.0-beta1

### ISSUE THREAD

**Issue by oschulz** [sunoru/Random123.jl#4]
Building Random123 on aarch64 with Julia v1.6.0-beta1 fails with

```
error: couldn't allocate output register for constraint '{ax}'
```

**Comment by oschulz** [comment]
@sunoru , are you still maintaining this package? I have some code that depends on Random123 a lot.

**Comment by sunoru** [comment]
Ah, yes, I am still maintaining it. Let me look into the problem.

BTW, I'm sorry I missed the other issue and will look into that as well.

**Comment by oschulz** [comment]
Thanks @sunoru !

**Comment by sunoru** [comment]
Looks like there have been some changes in the intrinsic functions, so the AESNI and ARS generators don't work on many platforms right now. Do you have to use these two RNGs? If not, I think you can just use the other RNGs normally, while I'm fixing this problem.

**Comment by oschulz** [comment]
No, I don't use AESNI and ARS, but the problem is that the package won't build properly without them, blocking the build process of other packages. Do you think it would make sense to split the package in two, a pure-Julia one for Philox & friends and another one with binary deps for AESNI and ARS?

**Comment by sunoru** [comment]
Sorry I missed your reply again...! Please update the package after the new version is registered: https://github.com/JuliaRegistries/General/pull/28454

Originally I added a method to control if AESNI and ARS are enabled by setting an environment variable and rebuilding the package, but then I found that in newer versions of Julia, it appears to be unstable on all the platforms (and it is so complicated to debug that I want to refactor related code sometime). Therefore, **all the parts of this package that are relying on AES-NI are disabled for now.**

**Comment by pkofod** [comment]
Hi @sunoru ! Just pinging you because you need to update your compact bounds as mentioned in the General PR. Thanks

**Comment by oschulz** [comment]
@sunoru Seems to run fine now on aarch64 with Julia v1.6.0-beta1 - thanks a lot!

**Comment by sunoru** [comment]
@oschulz glad to hear that!

I have been refactoring the AES-NI related RNGs using pure Julia (without any binary dependencies) and it seems to work well on different platforms. A new release will also be published soon.

**Comment by oschulz** [comment]
Oh, very cool! I think Random123 is very important, since it allows for reproducible random number generation in parallel applications.
