### ISSUE TITLE
Move to the JuliaRandom org?

### ISSUE THREAD

**Issue by ViralBShah** [sunoru/Random123.jl#6]
@sunoru Would you be ok with moving to JuliaRandom? We'll get you the owner bit there as well.

cc @rfourquet

**Comment by sunoru** [comment]
Sure, I'd love to. Maybe we can move all my three packages (Random123.jl, RandomNumbers.jl, and VSL.jl) that are related to RNG?

**Comment by ViralBShah** [comment]
@rfourquet It would be great if you can make @sunoru and me, both, owners of JuliaRandom. Thanks!

**Comment by ViralBShah** [comment]
We also have https://github.com/JuliaRNGs, but it looks like JuliaRandom is where everything should go.

**Comment by andreasnoack** [comment]
Done!
