### ISSUE TITLE
Build crashes due to missing AEC intrinsic

### ISSUE THREAD

**Issue by david-macmahon** [sunoru/Random123.jl#8]
Building Random123 (v1.4.0) crashes for me on an x86_64 system withOUT `aes` in the CPU flags (as seen in `/proc/cpuinfo`) with this error message:
```
LLVM ERROR: Cannot select: intrinsic %llvm.x86.aesni.aeskeygenassist
```
It builds fine for me on a system that does have `aes` in the CPU flags.

**Comment by sunoru** [comment]
Hi, thanks for reporting this. I didn't realize that the building process would just crash if the intrinsic was not found.

This should be fixed after https://github.com/JuliaRegistries/General/pull/38855 is merged. Sorry for the inconvenience.

**Comment by david-macmahon** [comment]
I have confirmed that this resolved the problem.  Thanks!
